global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'btg-core-api'
    static_configs:
      - targets: ['core:8080']
    metrics_path: /metrics

  - job_name: 'btg-consumer-ms'
    static_configs:
      - targets: ['ms:8081']
    metrics_path: /metrics
